image: ubuntu
build: off
install:
  - pip3 install flask gunicorn requests
  - pip3 install flask-bootstrap
  - pip3 install flask-wtf
  - pip3 install pillow
before_test:
  - chmod +x st.sh
test_script:

  - ./st.sh